# Generated by Django 4.2.1 on 2024-01-08 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubQuestion',
        ),
    ]
