# Generated by Django 4.2.1 on 2023-12-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0003_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField(default='')),
                ('mquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.question')),
            ],
        ),
    ]
