# Generated by Django 4.2.1 on 2024-01-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0003_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
