# Generated by Django 4.2.1 on 2024-01-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coding', '0004_delete_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Python',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=100, verbose_name='Chapter Name')),
                ('content', models.TextField(verbose_name='Content')),
            ],
        ),
    ]
