# Generated by Django 4.2.1 on 2024-01-08 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField(default='')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.python')),
            ],
        ),
    ]
