# Generated by Django 4.2.1 on 2024-01-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0007_pythonquestion_mcq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('content', models.TextField(verbose_name='')),
                ('language', models.CharField(max_length=50, verbose_name='Language')),
            ],
        ),
        migrations.AlterField(
            model_name='pythonquestion',
            name='mcq',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MCQ'),
        ),
    ]
