# Generated by Django 4.2.1 on 2023-12-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collocation',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collocation',
            name='usage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Usage'),
        ),
    ]
