# Generated by Django 4.2.1 on 2023-12-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collocation',
        ),
    ]
