# Generated by Django 4.2.1 on 2023-06-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='synonyms',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
