# Generated by Django 4.2.1 on 2023-12-30 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_collocation_context_collocation_usage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collocation',
        ),
    ]
