# Generated by Django 4.2.1 on 2023-06-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_words_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='forms',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
