# Generated by Django 4.2.1 on 2023-06-25 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_rename_words_word_revise'),
    ]

    operations = [
        migrations.AddField(
            model_name='revise',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
