# Generated by Django 4.2.1 on 2024-01-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_collocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='collocation',
            name='context_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collocation',
            name='context_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collocation',
            name='context_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collocation',
            name='context_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collocation',
            name='entry_pos_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collocation',
            name='entry_pos_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collocation',
            name='entry_pos_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collocation',
            name='entry_pos_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collocation',
            name='examples_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collocation',
            name='examples_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collocation',
            name='examples_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collocation',
            name='examples_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collocation',
            name='ref_id',
            field=models.BooleanField(default=False),
        ),
    ]
