# Generated by Django 4.2.1 on 2024-01-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_collocation_context_1_collocation_context_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collocation',
            name='context_1',
        ),
        migrations.RemoveField(
            model_name='collocation',
            name='context_2',
        ),
        migrations.RemoveField(
            model_name='collocation',
            name='context_3',
        ),
        migrations.RemoveField(
            model_name='collocation',
            name='context_4',
        ),
        migrations.RemoveField(
            model_name='collocation',
            name='entry_pos_1',
        ),
        migrations.RemoveField(
            model_name='collocation',
            name='entry_pos_2',
        ),
        migrations.RemoveField(
            model_name='collocation',
            name='entry_pos_3',
        ),
        migrations.RemoveField(
            model_name='collocation',
            name='entry_pos_4',
        ),
        migrations.RemoveField(
            model_name='collocation',
            name='examples_1',
        ),
        migrations.RemoveField(
            model_name='collocation',
            name='examples_2',
        ),
        migrations.RemoveField(
            model_name='collocation',
            name='examples_3',
        ),
        migrations.RemoveField(
            model_name='collocation',
            name='examples_4',
        ),
        migrations.AddField(
            model_name='collocation',
            name='fields',
            field=models.TextField(default='', verbose_name='Fields'),
            preserve_default=False,
        ),
    ]
