# Generated by Django 4.2.1 on 2024-01-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0006_remove_collocation_context_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collocation',
            name='context',
        ),
        migrations.RemoveField(
            model_name='collocation',
            name='entry_pos',
        ),
        migrations.RemoveField(
            model_name='collocation',
            name='examples',
        ),
    ]
