# Generated by Django 4.2.1 on 2024-01-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0007_remove_collocation_context_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collocation',
            name='fields',
        ),
    ]
