# Generated by Django 4.2.1 on 2023-06-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0007_alter_word_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_root',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
