# Generated by Django 4.2.1 on 2024-01-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0008_remove_collocation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='collocation',
            name='fields',
            field=models.JSONField(default={}),
        ),
    ]
