# Generated by Django 4.2.1 on 2023-06-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0009_word_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='pic',
            field=models.ImageField(default='', upload_to='dictionary'),
            preserve_default=False,
        ),
    ]
