# Generated by Django 4.2.1 on 2023-06-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0010_alter_word_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='dictionary'),
        ),
    ]
