# Generated by Django 4.2.1 on 2023-06-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0011_alter_word_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='dictionary/'),
        ),
    ]
