# Generated by Django 4.2.1 on 2023-06-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0012_alter_word_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='synonyms',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
