# Generated by Django 4.2.1 on 2023-07-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0013_alter_word_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='pic_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
