# Generated by Django 4.2.1 on 2023-07-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0014_word_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
