# Generated by Django 4.2.1 on 2023-07-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0015_alter_word_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='definition2',
            new_name='definition_hindi',
        ),
    ]
