# Generated by Django 4.2.1 on 2023-07-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0016_rename_definition2_word_definition_hindi'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='compare',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
