# Generated by Django 4.2.1 on 2023-07-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0017_word_compare'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='pronounce_hindi',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronounce',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
