# Generated by Django 4.2.1 on 2023-07-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0020_delete_question_exercise_answer_alter_exercise_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='question_type',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
