# Generated by Django 4.2.1 on 2023-07-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0021_exercise_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='question_type',
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('fill', 'Blanks Filling'), ('choice', 'Multiple Choice')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
