# Generated by Django 4.2.1 on 2023-07-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0022_remove_exercise_question_type_exercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='fill_values',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
