# Generated by Django 4.2.1 on 2023-07-06 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0024_post_fill_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='fill_values',
        ),
    ]
