# Generated by Django 4.2.1 on 2023-07-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0025_remove_exercise_fill_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fill_values',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
