# Generated by Django 4.2.1 on 2023-07-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0028_topic_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fill_values',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
