# Generated by Django 4.2.1 on 2023-07-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0029_alter_post_fill_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='def_inf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='root_pos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
