# Generated by Django 4.2.1 on 2023-07-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0032_exchoice_notification_revise_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='answer',
        ),
    ]
