# Generated by Django 4.2.1 on 2023-07-21 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0034_exercise_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
