# Generated by Django 4.2.1 on 2023-07-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0035_rename_date_created_post_created_at_post_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
