# Generated by Django 4.2.1 on 2023-07-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0036_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('words', models.ManyToManyField(to='languages.word')),
            ],
        ),
    ]
