# Generated by Django 4.2.1 on 2023-07-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0039_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='pic',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
