# Generated by Django 4.2.1 on 2023-07-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0040_quote_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='tip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='pic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
