# Generated by Django 4.2.1 on 2023-07-22 19:02

from django.db import migrations, models
import django.db.models.deletion
import languages.models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0041_word_tip_alter_quote_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='tipp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=languages.models.content_file_name),
        ),
    ]
