# Generated by Django 4.2.1 on 2023-07-23 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0042_word_tipp_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='tipp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='languages.post'),
        ),
    ]
