# Generated by Django 4.2.1 on 2023-07-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0044_alter_exercise_choice_delete_exchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='target_values',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
