# Generated by Django 4.2.1 on 2023-07-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0045_exercise_target_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=models.CharField(blank=True, choices=[('a1', 'Beginner'), ('a2', 'Pre Intermediate'), ('b1', 'Intermediate'), ('b2', 'Upper Intermediate'), ('c1', 'Advanced'), ('c2', 'Proficient')], default='', max_length=50, null=True),
        ),
    ]
