# Generated by Django 4.2.1 on 2023-07-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0046_exercise_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.CharField(blank=True, choices=[('animals', 'animals')], default='', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Vocabulary',
        ),
    ]
