# Generated by Django 4.2.1 on 2023-07-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0047_word_category_delete_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='pos',
            field=models.CharField(blank=True, choices=[('preposition', 'preposition'), ('helping verb', 'helping verb')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(blank=True, choices=[('animals', 'animals'), ('household', 'household')], default='', max_length=50, null=True),
        ),
    ]
