# Generated by Django 4.2.1 on 2023-07-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0048_exercise_pos_alter_word_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
