# Generated by Django 4.2.1 on 2023-08-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0051_word_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='hindi_usage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='compare',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='word',
            name='definition_hindi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronounce',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronounce_hindi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='synonyms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
