# Generated by Django 4.2.1 on 2023-08-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0052_word_hindi_usage_alter_word_compare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='definition_urdu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
