# Generated by Django 4.2.1 on 2023-11-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0053_word_definition_urdu'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='context',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='word',
            name='pic_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
