# Generated by Django 4.2.1 on 2023-12-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0056_word_antonyms_word_basic_definition_alter_word_forms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='tipp',
        ),
    ]
