# Generated by Django 4.2.1 on 2023-12-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0057_remove_word_tipp'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='related_post',
            field=models.ManyToManyField(blank=True, null=True, to='languages.post'),
        ),
    ]
