# Generated by Django 4.2.1 on 2023-12-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0058_word_related_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='context',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='related_post',
            field=models.ManyToManyField(blank=True, to='languages.post'),
        ),
    ]
