# Generated by Django 4.2.1 on 2023-12-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0059_alter_word_context_alter_word_related_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='revise',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
