# Generated by Django 4.2.1 on 2023-12-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0060_revise_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='revise',
            name='revise',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='word',
            name='collocation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
