# Generated by Django 4.2.1 on 2023-12-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0062_collocation_remove_word_collocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesaurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('words', models.CharField(max_length=100, verbose_name='Words')),
            ],
        ),
    ]
