# Generated by Django 4.2.1 on 2023-12-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0063_thesaurus'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='level',
            field=models.CharField(blank=True, choices=[('a1', 'Beginner'), ('a2', 'Pre Intermediate'), ('b1', 'Intermediate'), ('b2', 'Upper Intermediate'), ('c1', 'Advanced'), ('c2', 'Proficient')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
