# Generated by Django 4.2.1 on 2023-07-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_image_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='is_friend',
            field=models.BooleanField(default=False),
        ),
    ]
