# Generated by Django 4.2.1 on 2023-07-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_friend_is_friend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
