# Generated by Django 4.2.1 on 2023-07-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='fri',
            new_name='friend',
        ),
    ]
