# Generated by Django 4.2.1 on 2023-07-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_fri_friend_friend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
