# Generated by Django 4.2.1 on 2023-07-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(choices=[('studend', 'student'), ('teacher', 'teacher')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
