# Generated by Django 4.2.1 on 2023-07-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_ex_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ex_done',
        ),
    ]
