# Generated by Django 4.2.1 on 2023-07-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_notification_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='sender',
        ),
    ]
