# Generated by Django 4.2.1 on 2023-07-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_notification_receiver_alter_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='highest_degree',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
