# Generated by Django 4.2.1 on 2023-07-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_profile_highest_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ex_err',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
