# Generated by Django 4.2.1 on 2023-07-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_profile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
