# Generated by Django 4.2.1 on 2023-08-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_profile_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, choices=[('student', 'student'), ('teacher', 'teacher'), ('employed', 'employed'), ('self employed', 'self employed')], max_length=50, null=True),
        ),
    ]
